---
ID: "8e298a4a-8749-436d-a66f-8714c50e0f5c"
Parent: "73340012-f038-4f8e-88e7-be0f0fdf5a5b"
Template: "73340012-f038-4f8e-88e7-be0f0fdf5a5b"
Path: /sitecore/templates/Uniform Platform Canvas/DataTypePurgeRule/__Standard Values
DB: master
SharedFields:
- ID: "f550cc50-215d-47d5-a90e-2a44da9e83fb"
  Hint: rootPath
  Value: *
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230323T101438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
